logging:
  num_ims_per_log: 500
  num_ims_per_save_image: 100000
  num_ims_per_checkpoint: 200000
max_imsize: 128
use_full_validation: False
load_fraction_of_dataset: True
dataset: celeba-HQ
train_config:
  transition_iters: 600000
  learning_rate: 0.00175
  amp_opt_level: O1
  batch_size_schedule:
    4: 128
    8: 128
    16: 128
    32: 64
    64: 32
    128: 16
    256: 8
    512: 4
    1024: 4

models:
  start_channel_size: 256
  latent_size: 256
  image_channels: 3
  generator:
    running_average_decay: 0.999
  discriminator:
    structure: normal

